name: Docker Compose Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DB_HOST }}://${{ secrets.DB_USER}}:${{ secrets.DB_PASS }}@localhost:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
    services:
      db:
        image: postgres:16-alpine3.22
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME  }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Wait for PostgreSQL to be healthy
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.DB_USER }}; do
            echo "Waiting for database..."
            sleep 2
          done

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
