name: Docker Compose Action

on: [push]

jobs:
  test:
  runs-on: ubuntu-latest

  env:
    DATABASE_URL: ${{secrets.DB_HOST }}://${{ secrets.DB_USER}}:${{ secrets.DB_PASS }}@localhost:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
  services:
    db:
      image: postgres:16-alpine3.22
      env:
        POSTGRES_USER: ${{ secrets.DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        POSTGRES_DB: ${{ secrets.DB_NAME  }}
      ports:
        - 5432:5432

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
