name: Docker Compose Action

on:
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord notification
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: |
          🚀 **Novo Pull Request!** 🚀
          Um novo PR foi feito em **${{ github.repository }}** na branch **`${{ github.head_ref }}`**!
          🔗 Acesse o PR aqui: [Clique aqui para acessar]( ${{ github.event.pull_request.html_url }})
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run tests
        run: go test ./api/v1/...

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
